//! aiapp-cli: the command-line entry point for aiapp-mb.
//!
//! Pipeline orchestration:
//! `create` description → MoonBit project (with `.aiapp` manifest);
//! `build` MoonBit project → WASM → `.aiapp` package;
//! `go` one-shot end-to-end description → `.aiapp` package.
//!
//! Templates: `aiapp create "description" -t calculator` uses a predefined template.

use std::path::PathBuf;
use std::process::ExitCode;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

use aiapp_build::{build, BuildConfig};
use aiapp_gen::{generate_source, write_project, GenConfig, TEMPLATES};
use aiapp_pack::brand::BrandOverrides;
use aiapp_pack::{pack, PackConfig, PackTarget};

#[derive(Parser)]
#[command(
    name = "aiapp",
    version,
    about = "aiapp-mb: generate apps from natural language in one step → MoonBit source → WASM bytecode → .aiapp package"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Description → generate a MoonBit project (including the aiapp.json manifest)
    Create {
        /// Natural-language description of the app
        description: String,
        /// Project output directory
        #[arg(short, long, default_value = "generated")]
        output: PathBuf,
        /// App template (optional)
        /// Available templates: minimal, calculator, todo, image-filter
        #[arg(short, long, default_value = "minimal")]
        template: String,
        /// List available templates
        #[arg(long)]
        list_templates: bool,
    },
    /// MoonBit project → WASM bytecode → .aiapp package
    Build {
        /// Project directory
        #[arg(default_value = ".")]
        dir: PathBuf,
        /// Compilation target
        #[arg(short, long, default_value = "wasm-gc")]
        target: String,
        /// Whether to do a release build
        #[arg(long)]
        release: bool,
        /// Copy the WASM artifact to the given path
        #[arg(short, long)]
        output: Option<PathBuf>,
        /// Skip the .aiapp packaging step
        #[arg(long)]
        no_package: bool,
    },
    /// End-to-end: description → generate project → compile WASM → .aiapp package
    Go {
        /// Natural-language description of the app
        description: String,
        /// Project output directory
        #[arg(short, long, default_value = "generated")]
        output: PathBuf,
        /// App template
        #[arg(short, long, default_value = "minimal")]
        template: String,
        /// Compilation target
        #[arg(long, default_value = "wasm-gc")]
        target: String,
    },
    /// Turn a .aiapp package into a standalone app project (Phase 3: Tauri desktop / Capacitor mobile, with brand customization)
    Pack {
        /// `.aiapp` package directory
        pkg: PathBuf,
        /// Pack target: `tauri` (desktop .exe/.dmg/.deb) or `capacitor` (mobile .apk/.ipa)
        #[arg(short, long, default_value = "tauri")]
        target: String,
        /// Output directory (default `<pkg parent>/<name>-<target>`)
        #[arg(short, long)]
        out: Option<PathBuf>,
        /// App display name (brand name, defaults to the manifest name)
        #[arg(long)]
        name: Option<String>,
        /// Unique identifier (e.g. com.example.hello, defaults to aiapp.<app_id>)
        #[arg(long)]
        identifier: Option<String>,
        /// App version (defaults to the manifest version)
        #[arg(long)]
        version: Option<String>,
        /// App description
        #[arg(long)]
        description: Option<String>,
        /// Author
        #[arg(long)]
        author: Option<String>,
        /// Brand icon (PNG, copied into the shell project; a placeholder icon is generated by default)
        #[arg(long)]
        icon: Option<PathBuf>,
        /// Homepage / user custom domain
        #[arg(long)]
        homepage: Option<String>,
    },
    /// List available templates
    #[command(name = "templates")]
    ListTemplates,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    let result = match cli.command {
        Command::Create {
            description,
            output,
            template,
            list_templates,
        } => {
            if list_templates {
                cmd_list_templates();
                return ExitCode::SUCCESS;
            }
            cmd_create(&description, &output, &template)
        }
        Command::Build {
            dir,
            target,
            release,
            output,
            no_package,
        } => cmd_build(&dir, &target, release, output.as_deref(), no_package),
        Command::Go {
            description,
            output,
            template,
            target,
        } => cmd_go(&description, &output, &template, &target),
        Command::Pack {
            pkg,
            target,
            out,
            name,
            identifier,
            version,
            description,
            author,
            icon,
            homepage,
        } => cmd_pack(
            &pkg,
            &target,
            out.as_deref(),
            name.as_deref(),
            identifier.as_deref(),
            version.as_deref(),
            description.as_deref(),
            author.as_deref(),
            icon.as_deref(),
            homepage.as_deref(),
        ),
        Command::ListTemplates => {
            cmd_list_templates();
            return ExitCode::SUCCESS;
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}

/// List available templates.
fn cmd_list_templates() {
    println!("Available templates:");
    println!("{:-<40}", "");
    for (name, desc) in TEMPLATES {
        println!("  {:<15} {}", name, desc);
    }
    println!("{:-<40}", "");
    println!("Usage: aiapp create \"description\" -t <template-name>");
}

/// create: generate a MoonBit project (including the aiapp.json manifest).
fn cmd_create(description: &str, output: &PathBuf, template: &str) -> Result<()> {
    let config = GenConfig::from_env();
    println!(
        "[1/2] Generating MoonBit project (backend: {}, template: {})...",
        match config.backend {
            aiapp_gen::Backend::Mock => "mock",
            aiapp_gen::Backend::OpenAi => "openai",
            aiapp_gen::Backend::Pro => "pro",
        },
        template
    );
    let source = generate_source(description, &config, template)
        .with_context(|| "AI generation of MoonBit source failed")?;
    write_project(output, description, &source, template)
        .with_context(|| format!("Failed to write project directory {}", output.display()))?;
    println!("[2/2] Project generated: {}", output.display());
    println!("      Manifest: {}/aiapp.json", output.display());
    println!("      Next: aiapp build {}", output.display());
    Ok(())
}

/// build: compile to WASM and package as .aiapp.
fn cmd_build(
    dir: &PathBuf,
    target: &str,
    release: bool,
    output: Option<&std::path::Path>,
    no_package: bool,
) -> Result<()> {
    let config = BuildConfig {
        target: target.into(),
        release,
        package: !no_package,
        output: None,
        moon_bin: std::path::PathBuf::from("moon"),
    };
    println!("[1/2] Running moon build --target {target} ...");
    let out = build(dir, &config).with_context(|| format!("Failed to build project {}", dir.display()))?;
    let bytes = std::fs::metadata(&out.wasm)?.len();
    println!("[2/2] WASM artifact: {} ({} bytes)", out.wasm.display(), bytes);

    if let Some(out_path) = output {
        std::fs::create_dir_all(out_path.parent().unwrap_or_else(|| std::path::Path::new(".")))?;
        std::fs::copy(&out.wasm, out_path)
            .with_context(|| format!("Failed to copy artifact to {}", out_path.display()))?;
        println!("      Copied to: {}", out_path.display());
    }

    if let Some(aiapp_path) = &out.aiapp {
        let aiapp_bytes = dir_size(aiapp_path);
        println!("      .aiapp package: {} ({} bytes)", aiapp_path.display(), aiapp_bytes);
    }

    Ok(())
}

/// go: end-to-end description → .aiapp package.
fn cmd_go(description: &str, output: &PathBuf, template: &str, target: &str) -> Result<()> {
    let config = GenConfig::from_env();
    println!(
        "[1/3] Generating MoonBit project (backend: {}, template: {})...",
        match config.backend {
            aiapp_gen::Backend::Mock => "mock",
            aiapp_gen::Backend::OpenAi => "openai",
            aiapp_gen::Backend::Pro => "pro",
        },
        template
    );
    let source = generate_source(description, &config, template)
        .with_context(|| "AI generation of MoonBit source failed")?;
    write_project(output, description, &source, template)
        .with_context(|| format!("Failed to write project directory {}", output.display()))?;
    println!("[2/3] Project generated: {}", output.display());

    let build_config = BuildConfig {
        target: target.into(),
        release: false,
        package: true,
        output: None,
        moon_bin: std::path::PathBuf::from("moon"),
    };
    println!("[3/3] Running moon build --target {target} ...");
    let out = build(output, &build_config)
        .with_context(|| format!("Failed to build project {}", output.display()))?;
    let bytes = std::fs::metadata(&out.wasm)?.len();
    let aiapp_msg = match &out.aiapp {
        Some(p) => format!(".aiapp package: {}", p.display()),
        None => "".into(),
    };
    println!("      WASM bytecode: {} ({} bytes) {}", out.wasm.display(), bytes, aiapp_msg);
    println!("      Done!");
    Ok(())
}

/// pack: turn a .aiapp package into a standalone app project (Tauri desktop / Capacitor mobile, with brand customization).
#[allow(clippy::too_many_arguments)]
fn cmd_pack(
    pkg: &std::path::Path,
    target: &str,
    out: Option<&std::path::Path>,
    name: Option<&str>,
    identifier: Option<&str>,
    version: Option<&str>,
    description: Option<&str>,
    author: Option<&str>,
    icon: Option<&std::path::Path>,
    homepage: Option<&str>,
) -> Result<()> {
    let target = PackTarget::parse(target).map_err(anyhow::Error::msg)?;
    let config = PackConfig {
        target,
        out_dir: out.map(std::path::PathBuf::from),
        brand: BrandOverrides {
            name: name.map(str::to_string),
            identifier: identifier.map(str::to_string),
            version: version.map(str::to_string),
            description: description.map(str::to_string),
            author: author.map(str::to_string),
            homepage: homepage.map(str::to_string),
            icon: icon.map(std::path::PathBuf::from),
        },
    };
    println!("[1/1] Generating standalone app project (target: {})...", target.as_str());
    let out_dir = pack(pkg, &config).with_context(|| format!("Failed to pack {}", pkg.display()))?;
    println!("      Project generated: {}", out_dir.display());
    println!("      Next:");
    match target {
        PackTarget::Tauri => {
            println!("        cd {} && cd src-tauri && npx tauri build", out_dir.display());
            println!("        Artifacts: src-tauri/target/release/bundle/<platform>/");
        }
        PackTarget::Capacitor => {
            println!("        cd {} && npm install && npx cap add android && npx cap build android", out_dir.display());
            println!("        iOS: npx cap add ios && npx cap build ios");
        }
    }
    Ok(())
}

/// Calculate the directory size (bytes).
fn dir_size(path: &std::path::Path) -> u64 {
    let mut total = 0u64;
    if let Ok(entries) = std::fs::read_dir(path) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_file() {
                total += std::fs::metadata(&p).map(|m| m.len()).unwrap_or(0);
            }
        }
    }
    total
}
