//! Local mock backend: no external AI dependency, returns fixed sample source for offline demos and tests.

use crate::GenError;

/// Return a runnable MoonBit sample program.
pub fn generate(desc: &str) -> Result<String, GenError> {
    let note = desc.trim();
    let line = if note.is_empty() {
        "  println(\"Hello from aiapp-mb\")\n".to_string()
    } else {
        format!("  println(\"aiapp-mb demo: {}\")\n", sanitize(note))
    };
    Ok(format!(
        "///| Generated by the aiapp-mb mock backend, description: {note}\nfn main {{\n{line}}}\n"
    ))
}

/// Strip characters that would break string literals.
fn sanitize(s: &str) -> String {
    s.replace('"', "'").replace('\\', "")
}
