//! MoonBit application template library.
//!
//! Provides several predefined MoonBit application templates as a basis and
//! examples for AI generation.
//! Supported templates: minimal (minimal), todo (todo), image-filter (image filter),
//! pomodoro (pomodoro timer), memory-game (memory match), tv-movies (family media list),
//! timestamp (timestamp converter).

/// List of available templates.
pub const TEMPLATES: &[(&str, &str)] = &[
    ("minimal", "Minimal: a Hello World style app"),
    ("todo", "Todo: a todo list manager with full CRUD"),
    ("image-filter", "Image filter: an image filtering app"),
    ("pomodoro", "Pomodoro: work/break timer that accumulates focus sessions"),
    ("memory-game", "Memory match: a card-matching game that records best scores"),
    ("tv-movies", "Family media list: categorized movie collection, TV/vehicle big-screen friendly"),
    ("timestamp", "Timestamp: convert between Unix timestamps and human-readable date/time"),
];

/// Return the corresponding MoonBit source for a template name.
pub fn get_template_source(name: &str, desc: &str) -> Option<String> {
    let source = match name {
        "minimal" => minimal_template(desc),
        "todo" => todo_template(desc),
        "image-filter" => image_filter_template(desc),
        "pomodoro" => pomodoro_template(desc),
        "memory-game" => memory_game_template(desc),
        "tv-movies" => tv_movies_template(desc),
        "timestamp" => timestamp_template(desc),
        _ => return None,
    };
    Some(source)
}

/// Generate the MoonBit source for the minimal template.
fn minimal_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: minimal
///| Generated by aiapp-mb

fn main {{
  println("Hello from aiapp-mb!")
  println("Description: {sanitized}")
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb minimal app: {sanitized}"
}}
"#,
        desc = desc,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the todo template.
fn todo_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: todo
///| Generated by aiapp-mb

/// Todo item
struct Todo {{
  id: Int
  title: String
  mut done: Bool
}}

/// Todo list
struct TodoList {{
  todos: Array[Todo]
  mut next_id: Int
}}

/// Create an empty todo list
pub fn TodoList::new() -> TodoList {{
  TodoList::{{ todos: [], next_id: 1 }}
}}

/// Add a todo
pub fn TodoList::add(self: TodoList, title: String) -> Unit {{
  let todo = Todo::{{ id: self.next_id, title: title, done: false }}
  self.todos.push(todo)
  self.next_id = self.next_id + 1
}}

/// Mark as completed
pub fn TodoList::complete(self: TodoList, id: Int) -> Unit {{
  for i in 0..<self.todos.length() {{
    if self.todos[i].id == id {{
      self.todos[i].done = true
    }}
  }}
}}

/// List all todos
pub fn TodoList::list(self: TodoList) -> String {{
  let mut result = "Todos:\n"
  for todo in self.todos {{
    let status = if todo.done {{ "[✓]" }} else {{ "[ ]" }}
    result = result + status + " " + todo.id.to_string() + ". " + todo.title + "\n"
  }}
  result
}}

fn main {{
  println("=== Todos ===")
  println("Description: {sanitized}")
  let list = TodoList::new()
  list.add("Learn MoonBit")
  list.add("Build WASM")
  list.add("Deploy app")
  list.complete(1)
  println(list.list())
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb todo app: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the image-filter template.
fn image_filter_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: image-filter
///| Generated by aiapp-mb

/// Pixel
struct Pixel {{
  r: Int
  g: Int
  b: Int
}}

/// Image
struct Image {{
  width: Int
  height: Int
  pixels: Array[Array[Pixel]]
}}

/// Create a test image (each row is a separate array to avoid row sharing)
pub fn make_test_image(w: Int, h: Int) -> Image {{
  let pixels : Array[Array[Pixel]] = []
  for i in 0..<h {{
    let row : Array[Pixel] = []
    for j in 0..<w {{
      row.push(Pixel::{{ r: 0, g: 0, b: 0 }})
    }}
    pixels.push(row)
  }}
  for i in 0..<h {{
    for j in 0..<w {{
      pixels[i][j] = Pixel::{{
        r: (i * 255) / h,
        g: (j * 255) / w,
        b: (i + j) * 255 / (w + h),
      }}
    }}
  }}
  Image::{{ width: w, height: h, pixels: pixels }}
}}

/// Grayscale filter
pub fn to_grayscale(img: Image) -> Image {{
  for i in 0..<img.height {{
    for j in 0..<img.width {{
      let p = img.pixels[i][j]
      let gray = (p.r + p.g + p.b) / 3
      img.pixels[i][j] = Pixel::{{ r: gray, g: gray, b: gray }}
    }}
  }}
  img
}}

/// Invert colors
pub fn invert(img: Image) -> Image {{
  for i in 0..<img.height {{
    for j in 0..<img.width {{
      let p = img.pixels[i][j]
      img.pixels[i][j] = Pixel::{{ r: 255 - p.r, g: 255 - p.g, b: 255 - p.b }}
    }}
  }}
  img
}}

fn main {{
  println("=== Image Filter ===")
  println("Description: {sanitized}")
  let img = make_test_image(4, 4)
  let w = img.width
  let h = img.height
  println("Original image: " + w.to_string() + "x" + h.to_string())
  let gray = to_grayscale(img)
  println("Grayscale filter applied")
  let inverted = invert(gray)
  println("Color inversion applied")
  println("Filter processing done!")
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb image-filter app: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the pomodoro template.
fn pomodoro_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: pomodoro
///| Generated by aiapp-mb

/// Pomodoro session type: Focus / Break
pub enum SessionType {{
  Focus
  Break
}}

/// Per-session pomodoro stats
pub struct PomodoroStat {{
  mut total_focus: Int
  mut total_break: Int
  mut sessions: Int
}}

/// Create empty stats
pub fn PomodoroStat::new() -> PomodoroStat {{
  PomodoroStat::{{ total_focus: 0, total_break: 0, sessions: 0 }}
}}

/// Record one focus session
pub fn PomodoroStat::record(self: PomodoroStat, ty: SessionType, minutes: Int) -> Unit {{
  self.sessions = self.sessions + 1
  match ty {{
    Focus => self.total_focus = self.total_focus + minutes
    Break => self.total_break = self.total_break + minutes
  }}
}}

/// Produce a formatted stats summary
pub fn PomodoroStat::summary(self: PomodoroStat) -> String {{
  "Total focus: " + self.total_focus.to_string() + " min, " +
  "Total break: " + self.total_break.to_string() + " min, " +
  "Sessions: " + self.sessions.to_string()
}}

fn main {{
  println("=== Focus Pomodoro ===")
  println("Description: {sanitized}")
  let stat = PomodoroStat::new()
  stat.record(Focus, 25)
  stat.record(Break, 5)
  stat.record(Focus, 25)
  println(stat.summary())
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb pomodoro app: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the memory-game template.
fn memory_game_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: memory-game
///| Generated by aiapp-mb

/// A card
pub struct Card {{
  id: Int
  symbol: String
  mut matched: Bool
}}

/// Memory matching game board
pub struct MemoryBoard {{
  cards: Array[Card]
  mut moves: Int
}}

/// Build a deck (symbols appear in pairs)
pub fn MemoryBoard::new() -> MemoryBoard {{
  let symbols : Array[String] = ["🍎", "🍌", "🍇", "🍊", "🍓", "🥑"]
  let cards : Array[Card] = []
  for i in 0..<symbols.length() {{
    cards.push(Card::{{ id: i * 2, symbol: symbols[i], matched: false }})
    cards.push(Card::{{ id: i * 2 + 1, symbol: symbols[i], matched: false }})
  }}
  MemoryBoard::{{ cards: cards, moves: 0 }}
}}

/// Number of unmatched cards remaining
pub fn MemoryBoard::remaining(self: MemoryBoard) -> Int {{
  let mut n = 0
  for c in self.cards {{
    if !(c.matched) {{ n = n + 1 }}
  }}
  n
}}

/// Try flipping two cards and check for a match
pub fn MemoryBoard::turn(self: MemoryBoard, a: Int, b: Int) -> Bool {{
  self.moves = self.moves + 1
  let ca = self.cards[a]
  let cb = self.cards[b]
  if ca.symbol == cb.symbol && a != b {{
    self.cards[a].matched = true
    self.cards[b].matched = true
    true
  }} else {{
    false
  }}
}}

fn main {{
  println("=== Family Memory Match ===")
  println("Description: {sanitized}")
  let board = MemoryBoard::new()
  println("Unmatched remaining: " + board.remaining().to_string() + " cards")
  let hit = board.turn(0, 1)
  println("Flip 0/1: " + (if hit {{ "matched" }} else {{ "unmatched" }}))
  println("Moves used: " + board.moves.to_string())
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb memory-game app: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the tv-movies template.
fn tv_movies_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: tv-movies
///| Generated by aiapp-mb

/// A movie entry
pub struct Movie {{
  title: String
  category: String
  mut favorite: Bool
}}

/// Movie list collection
pub struct MovieList {{
  movies: Array[Movie]
}}

/// Create a sample list
pub fn MovieList::new() -> MovieList {{
  MovieList::{{ movies: [
    Movie::{{ title: "Interstellar", category: "Sci-Fi", favorite: false }},
    Movie::{{ title: "Kung Fu Panda", category: "Animation", favorite: false }},
    Movie::{{ title: "A Bite of China", category: "Documentary", favorite: true }},
  ] }}
}}

/// Add a movie to favorites
pub fn MovieList::favorite(self: MovieList, index: Int) -> Unit {{
  self.movies[index].favorite = true
}}

/// Render a formatted movie list
pub fn MovieList::render(self: MovieList) -> String {{
  let mut result = "Movie list:\n"
  for i in 0..<self.movies.length() {{
    let m = self.movies[i]
    let star = if m.favorite {{ "★" }} else {{ "☆" }}
    result = result + star + " " + m.category + " · " + m.title + "\n"
  }}
  result
}}

fn main {{
  println("=== Family Media List ===")
  println("Description: {sanitized}")
  let list = MovieList::new()
  list.favorite(0)
  println(list.render())
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb tv-movies app: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Generate the MoonBit source for the timestamp converter template.
fn timestamp_template(desc: &str) -> String {
    format!(
        r#"///| App: {desc}
///| Template: timestamp
///| Generated by aiapp-mb

/// Return a demo message for the timestamp converter.
pub fn demo_info() -> String {{
  "Timestamp Converter: converts between Unix timestamps and human-readable date/time."
}}

fn main {{
  println(demo_info())
}}

/// App info
pub fn app_info() -> String {{
  "aiapp-mb timestamp converter: {sanitized}"
}}
"#,
        sanitized = sanitize(desc)
    )
}

/// Remove characters that would break string literals.
fn sanitize(s: &str) -> String {
    s.replace('"', "'").replace('\\', "").replace('\n', " ")
}